// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ItemCreate = {
    title: string;
    description?: (string | null);
};

export type ItemPublic = {
    title: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ItemsPublic = {
    data: Array<ItemPublic>;
    count: number;
};

export type ItemUpdate = {
    title?: (string | null);
    description?: (string | null);
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    username?: (string | null);
    bio?: (string | null);
    website?: (string | null);
    twitter?: (string | null);
    instagram?: (string | null);
    youtube?: (string | null);
    tiktok?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
    username?: (string | null);
    bio?: (string | null);
    website?: (string | null);
    twitter?: (string | null);
    instagram?: (string | null);
    youtube?: (string | null);
    tiktok?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

// ── Brand ────────────────────────────────────────────────────────────────────

export type BrandCreate = {
    name: string;
    category?: string;
    contact_name?: (string | null);
    contact_email?: (string | null);
    status?: string;
    notes?: (string | null);
};

export type BrandPublic = {
    name: string;
    category?: string;
    contact_name?: (string | null);
    contact_email?: (string | null);
    status?: string;
    notes?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type BrandsPublic = {
    data: Array<BrandPublic>;
    count: number;
};

export type BrandUpdate = {
    name?: (string | null);
    category?: (string | null);
    contact_name?: (string | null);
    contact_email?: (string | null);
    status?: (string | null);
    notes?: (string | null);
};

// ── Project ───────────────────────────────────────────────────────────────────

export type ProjectCreate = {
    title: string;
    type?: string;
    platform_status?: string;
    deadline?: (string | null);
    description?: (string | null);
    brand_id?: (string | null);
};

export type ProjectPublic = {
    title: string;
    type?: string;
    platform_status?: string;
    deadline?: (string | null);
    description?: (string | null);
    brand_id?: (string | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type ProjectsPublic = {
    data: Array<ProjectPublic>;
    count: number;
};

export type ProjectUpdate = {
    title?: (string | null);
    type?: (string | null);
    platform_status?: (string | null);
    deadline?: (string | null);
    description?: (string | null);
    brand_id?: (string | null);
};

// ── Collaborator ──────────────────────────────────────────────────────────────

export type CollaboratorCreate = {
    name: string;
    role: string;
};

export type CollaboratorPublic = {
    name: string;
    role: string;
    id: string;
};

export type CollaboratorsPublic = {
    data: Array<CollaboratorPublic>;
    count: number;
};

export type CollaboratorUpdate = {
    name?: (string | null);
    role?: (string | null);
};

// ── Task ──────────────────────────────────────────────────────────────────────

export type TaskCreate = {
    title: string;
    description?: (string | null);
    status?: string;
    priority?: string;
    due_date?: (string | null);
    project_id?: (string | null);
    assigned_to?: (string | null);
    collaborator_id?: (string | null);
};

export type TaskPublic = {
    title: string;
    description?: (string | null);
    status?: string;
    priority?: string;
    due_date?: (string | null);
    project_id?: (string | null);
    assigned_to?: (string | null);
    collaborator_id?: (string | null);
    collaborator?: (CollaboratorPublic | null);
    id: string;
    owner_id: string;
    created_at?: (string | null);
};

export type TasksPublic = {
    data: Array<TaskPublic>;
    count: number;
};

export type TaskUpdate = {
    title?: (string | null);
    description?: (string | null);
    status?: (string | null);
    priority?: (string | null);
    due_date?: (string | null);
    project_id?: (string | null);
    assigned_to?: (string | null);
    collaborator_id?: (string | null);
};

// ── Brands request/response types ────────────────────────────────────────────

export type BrandsReadBrandsData = { limit?: number; skip?: number };
export type BrandsReadBrandsResponse = BrandsPublic;
export type BrandsCreateBrandData = { requestBody: BrandCreate };
export type BrandsCreateBrandResponse = BrandPublic;
export type BrandsReadBrandData = { id: string };
export type BrandsReadBrandResponse = BrandPublic;
export type BrandsUpdateBrandData = { id: string; requestBody: BrandUpdate };
export type BrandsUpdateBrandResponse = BrandPublic;
export type BrandsDeleteBrandData = { id: string };
export type BrandsDeleteBrandResponse = Message;

// ── Projects request/response types ──────────────────────────────────────────

export type ProjectsReadProjectsData = { limit?: number; skip?: number };
export type ProjectsReadProjectsResponse = ProjectsPublic;
export type ProjectsCreateProjectData = { requestBody: ProjectCreate };
export type ProjectsCreateProjectResponse = ProjectPublic;
export type ProjectsReadProjectData = { id: string };
export type ProjectsReadProjectResponse = ProjectPublic;
export type ProjectsUpdateProjectData = { id: string; requestBody: ProjectUpdate };
export type ProjectsUpdateProjectResponse = ProjectPublic;
export type ProjectsDeleteProjectData = { id: string };
export type ProjectsDeleteProjectResponse = Message;

// ── Tasks request/response types ─────────────────────────────────────────────

export type TasksReadTasksData = { limit?: number; skip?: number };
export type TasksReadTasksResponse = TasksPublic;
export type TasksCreateTaskData = { requestBody: TaskCreate };
export type TasksCreateTaskResponse = TaskPublic;
export type TasksReadTaskData = { id: string };
export type TasksReadTaskResponse = TaskPublic;
export type TasksUpdateTaskData = { id: string; requestBody: TaskUpdate };
export type TasksUpdateTaskResponse = TaskPublic;
export type TasksDeleteTaskData = { id: string };
export type TasksDeleteTaskResponse = Message;

// ── Collaborators request/response types ─────────────────────────────────────

export type CollaboratorsReadCollaboratorsData = { limit?: number; skip?: number };
export type CollaboratorsReadCollaboratorsResponse = CollaboratorsPublic;
export type CollaboratorsCreateCollaboratorData = { requestBody: CollaboratorCreate };
export type CollaboratorsCreateCollaboratorResponse = CollaboratorPublic;
export type CollaboratorsReadCollaboratorData = { id: string };
export type CollaboratorsReadCollaboratorResponse = CollaboratorPublic;
export type CollaboratorsUpdateCollaboratorData = { id: string; requestBody: CollaboratorUpdate };
export type CollaboratorsUpdateCollaboratorResponse = CollaboratorPublic;
export type CollaboratorsDeleteCollaboratorData = { id: string };
export type CollaboratorsDeleteCollaboratorResponse = Message;

export type ItemsReadItemsData = {
    limit?: number;
    skip?: number;
};

export type ItemsReadItemsResponse = (ItemsPublic);

export type ItemsCreateItemData = {
    requestBody: ItemCreate;
};

export type ItemsCreateItemResponse = (ItemPublic);

export type ItemsReadItemData = {
    id: string;
};

export type ItemsReadItemResponse = (ItemPublic);

export type ItemsUpdateItemData = {
    id: string;
    requestBody: ItemUpdate;
};

export type ItemsUpdateItemResponse = (ItemPublic);

export type ItemsDeleteItemData = {
    id: string;
};

export type ItemsDeleteItemResponse = (Message);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);

// ── Public Profile ────────────────────────────────────────────────────────────

export type CreatorStats = {
    brands_count: number;
    projects_count: number;
    tasks_done: number;
    tasks_total: number;
};

export type CreatorProfile = {
    full_name: string | null;
    username: string;
    created_at: string | null;
    stats: CreatorStats;
};

export type PublicGetCreatorProfileData = { username: string };
export type PublicGetCreatorProfileResponse = CreatorProfile;
export type PublicGetCreatorBrandsData = { username: string };
export type PublicGetCreatorBrandsResponse = BrandsPublic;
export type PublicGetCreatorProjectsData = { username: string };
export type PublicGetCreatorProjectsResponse = ProjectsPublic;